name: Lore CI

on:
  push:
    paths: ['kb/**']
  pull_request:
    paths: ['kb/**']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run linter on KB
        run: |
          python kb/tools/lore_lint.py $(git ls-files 'kb/**/*.yaml' 'kb/**/*.yml' 'kb/**/*.json' || echo)
